name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-16.04
        timeout-minutes: 15
        strategy:
            matrix:
                version:
                    - '8.8'
                    - '8.7'
                    - '8.6'
                    - '8.5'
                    - '8.4'
                    - '8.3'
                    - '8.2'
                    - '8.1'
                    - '8.0'
                    - '7.7'
                    - '6.6'
                    - '5.5'
                variant:
                    - ''
                    - '/slim'
        steps:
            - uses: actions/checkout@v2
            -
                name: Build, test, deploy
                env:
                    PROCESS: ${{ matrix.version }}${{ matrix.variant }}
                run: tools/build_test.sh $PROCESS
